M48
; DRILL file {KiCad (6.0.1-0)} date Wednesday, January 18, 2023 at 10:23:19 AM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-18T10:23:19-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C6.500
%
G90
G05
T3
X150.0Y-74.5
T1
X149.35Y-54.4G85X150.65Y-54.4
G05
X149.35Y-65.6G85X150.65Y-65.6
G05
T2
X108.45Y-97.6G85X110.95Y-97.6
G05
X189.05Y-97.6G85X191.55Y-97.6
G05
T0
M30
